version: '3.8'

services:
  # The Database Service
  db:
    image: postgis/postgis:15-3.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-isitopen_db}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    # For production, you might want to expose this only to the backend or through a VPN
    # ports:
    #   - "5432:5432"

  # The Django Backend
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    # command: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 # Already in Dockerfile CMD
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-isitopen_db}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - TOMTOM_API_KEY=${TOMTOM_API_KEY}

volumes:
  postgres_data:
