# Generated by Django 5.2.11 on 2026-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_home_city_userprofile_home_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_subscription_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
