# Generated by Django 5.2.11 on 2026-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_savedplace_color_savedplace_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
