# Generated by Django 5.2.11 on 2026-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_categories_place_phone_place_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedplace',
            name='average_visit_length',
            field=models.IntegerField(blank=True, help_text='Average visit length in minutes', null=True),
        ),
    ]
