// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/bloc/calendar/calendar_data_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/models/place.dart' as _i3;
import 'package:frontend/models/saved_place.dart' as _i6;
import 'package:frontend/models/user.dart' as _i2;
import 'package:frontend/services/api_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlace_1 extends _i1.SmartFake implements _i3.Place {
  _FakePlace_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#setAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.User> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> register(
    String? username,
    String? password, {
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [username, password], {#email: email}),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(
                  #register,
                  [username, password],
                  {#email: email},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<List<_i3.Place>> searchPlaces(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPlaces, [query]),
            returnValue: _i5.Future<List<_i3.Place>>.value(<_i3.Place>[]),
          )
          as _i5.Future<List<_i3.Place>>);

  @override
  _i5.Future<_i3.Place> savePlace(_i3.Place? place) =>
      (super.noSuchMethod(
            Invocation.method(#savePlace, [place]),
            returnValue: _i5.Future<_i3.Place>.value(
              _FakePlace_1(this, Invocation.method(#savePlace, [place])),
            ),
          )
          as _i5.Future<_i3.Place>);

  @override
  _i5.Future<void> bookmarkPlace(String? tomtomId, {String? customName}) =>
      (super.noSuchMethod(
            Invocation.method(
              #bookmarkPlace,
              [tomtomId],
              {#customName: customName},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteBookmark(String? tomtomId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBookmark, [tomtomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.SavedPlace>> getBookmarks() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, []),
            returnValue: _i5.Future<List<_i6.SavedPlace>>.value(
              <_i6.SavedPlace>[],
            ),
          )
          as _i5.Future<List<_i6.SavedPlace>>);

  @override
  _i5.Future<_i2.User> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#getProfile, [])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateProfile(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue: _i5.Future<_i2.User>.value(
              _FakeUser_0(this, Invocation.method(#updateProfile, [user])),
            ),
          )
          as _i5.Future<_i2.User>);

  @override
  _i5.Future<void> togglePinPlace(String? tomtomId, bool? isPinned) =>
      (super.noSuchMethod(
            Invocation.method(#togglePinPlace, [tomtomId, isPinned]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleCheckItOut(String? tomtomId, bool? isCheckItOut) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCheckItOut, [tomtomId, isCheckItOut]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateBookmarkGraphic(
    String? tomtomId,
    String? icon,
    String? color, {
    String? customName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBookmarkGraphic,
              [tomtomId, icon, color],
              {#customName: customName},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateVisitLength(String? tomtomId, int? visitLength) =>
      (super.noSuchMethod(
            Invocation.method(#updateVisitLength, [tomtomId, visitLength]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getCalendarFromUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#getCalendarFromUrl, [url]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getCalendarFromUrl, [url]),
              ),
            ),
          )
          as _i5.Future<String>);
}
